### ISSUE TITLE
Tidy Data!

### ISSUE THREAD

**Issue by sol-bixby** [sol-bixby/Chemistry_313_ICPMS_Lab#1]
ICMPS_merged is the ICPMS tidy data, AA_tidy is the AA tidy data. I merged the Sample Key and the AA data, then filtered out the non-sample data. Since the datasets were fairly tidy to start with they didn't need much modification.

**Comment by vestoj** [comment]
Nice job! Your code looks great, and your data very tidy. You might consider changing the column headers to something slightly more parsable in R but it's totally up to you, it shouldn't affect your analysis either way!
